name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: submodules
        run: |
          git submodule update --init --depth 1

      - name: linux setup and dependencies
        run: |
          sudo apt update
          sudo apt -y install libgtk-3-dev pkgconf

      - name: configure linux
        run: |
          cmake -S . -B build/linux -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: build linux
        run: |
          cmake --build build/linux -j$(nproc)

      - name: install linux
        run: |
          cmake --install build/linux --prefix out-linux

      - name: linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux_build
          path: out-linux

  build_msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: msys2 {0}
            
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-gtk3

      - name: submodules
        run: |
          git submodule update --init --depth 1

      - name: configure msys2
        run: |
          cmake -S . -B build/msys2 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: build msys2
        run: |
          cmake --build build/msys2 -j$(nproc)

      - name: install msys2
        run: |
          cmake --install build/msys2 --prefix out-msys2

      - name: msys2 build
        uses: actions/upload-artifact@v4
        with:
          name: msys2_build
          path: out-msys2
